---
#installing nodejs from following website
# https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server
- hosts: all
  become: yes
  tasks:
  - name: updating apt packages
    apt:
      update_cache: yes
- hosts: app
  become: yes
  vars:
    folderpath: /home/ansible/nodesetup
  tasks:
  - name: creating a directory
    file: 
      path: "{{ folderpath }}"
      state: directory
      mode: 0755
  - name: installing nodejs
    apt:
      name: "{{ item }}"
      state: present
    with_items:
     - nodejs
     - build-essential

      
  
      