---
#installing tomcat from
#https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-7-on-ubuntu-14-04-via-apt-get
- hosts: all
  become: yes
  vars:
    xmx: 512
    maxpersize: 256
  tasks:
  - name: updating the apt packages
    apt:
      update_cache: yes
- hosts: app
  become: yes
  tasks:
  - name: installing tomcat7
    apt:
    name: tomcat7
    state: present
  - name: creating template
    template:
      src: templates/tomcat7.j2
      dest: /etc/default/tomcat7
      mode: 0644
  - name: restarting tomcat
    service:
      name: tomcat7
      action: started
  - name: installing additional packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - tomcat7-docs
      - tomcat7-admin
      - tomcat7-examples
  - name: installing java development kit
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - default-jdk
      - ant
      - git
    
